### ISSUE TITLE
linux-gtk-configure.sh script appears to be broken

### ISSUE THREAD

**Issue by Amadiro** [kmeisthax/icCanvas#18]
$ ./linux-gtk-configure.sh                                                                                             
CMake Error: The source directory "/home/amadiro/icCanvas/frontends/gtk/platform/gnulinux-desktop" does not exist.                              
Specify --help for usage, or press the help button on the CMake GUI.

The linux-gtk-debug-configure.sh seems to work fine.

**Comment by kmeisthax** [comment]
Try it now. I usually only use the debug script...

**Comment by Amadiro** [comment]
That seems to have fixed it, although now I'm getting:

    error: Package `gee-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories

from looking around, the latest version of libgee appears to be 0.16. Is this perhaps another bug in the script?

**Comment by kmeisthax** [comment]
Ubuntu installs Gee as version 1.0... for some reason. Assuming you installed the necessary libgee  development packages, could you report what version of gee you have installed?

**Comment by Amadiro** [comment]
I appear to have 0.16.1, according to pacman.

**Comment by kmeisthax** [comment]
Wait how the eff did that close the issue? I guess if you use "fix" in your commit message?!

**Comment by Amadiro** [comment]
Well, both the debug and the non-debug variant seem to build fine for me now, so I'll close the issue.
