### ISSUE TITLE
icCanvasGtk crashes on startup

### ISSUE THREAD

**Issue by Amadiro** [kmeisthax/icCanvas#19]
Applies both to the debug and the non-debug build. Immediately crashes on startup.

$ ./icCanvasGtk 
icCanvasGtk: /home/amadiro/icCanvas/build/linux-gtk-debug/ext/eigen/src/Eigen/Eigen/src/Core/DenseStorage.h:78: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = float; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
Aborted (core dumped)

built from master, c9e7ad6d8181e877afe7153d1a1744cf0fe976ef

**Comment by kmeisthax** [comment]
Yay for me using older C++ libraries that don't support the shiny new alignment toys. This should fix the issue.

(I'm more wondering why this didn't trip me up... I'm compiling on 64-bit everywhere - Ubuntu, OSX, and Arch; so I assume this is a 32-bit issue.)

**Comment by Amadiro** [comment]
Woops, yeah, I probably should've mentioned that :) I compiled this one on a 32-bit system. It compiles & runs fine now though, thanks!
